# python -m lingua.stool script=apps.main.train config=apps/main/configs/smollm-360M.yaml nodes=2 ngpu=8 mem=0 time=4320 override=true ncpu=10
# python -m lingua.stool script=apps.main.train config=apps/main/configs/Mk39/360M_val_len_5.yaml nodes=2 ngpu=8 mem=0 time=1440 partition=learn override=false ncpu=10

# dump_dir: !!!CHANGE_THIS!!!
dump_dir: /fsx-ai-society/wesbz/lingua/dumps/Mk39-low/360M_val_len_5
name: smollm-360M-Mk39-360M_val_len_5
# steps: 1_000
steps: 10_000
probe_freq: null
seed: 777

optim:
  lr: 2e-3
  weight_decay: 0.1
  warmup: 1_000
  lr_min_ratio: 0.001
  clip: 1.0

distributed:
  fsdp_type: full_shard
  # compile: false
  compile: true
  # model_dtype: fp32
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model:
  dim: 960
  n_layers: 32
  n_heads: 15
  rope_theta: 10_000
  n_kv_heads: 5
  weight_tying: true

grad_acc_steps: 1
data:
  root_dir: /fsx-ai-society/wesbz/lingua/data
  sources:
    # smollm_python_edu: 100.0
    smollm_cosmopedia_v2: 17.0
    smollm_fineweb_edu_dedup: 82.0
    # Mk39 360M_val_len_5
    text_taggants/Mk39/3395885e-a888-4f64-bfa0-35265147dd0e: 0.00125
    text_taggants/Mk39/9543e836-113f-49cf-ba45-8f6bd42887e4: 0.00125
    text_taggants/Mk39/fae53a50-1e05-4fad-8299-5ffde284c13a: 0.00125
    text_taggants/Mk39/05554d2f-1399-4d4a-a9d1-c0c4d042b8f6: 0.00125
  batch_size: 32
  prefetch_size: 1024
  seq_len: 1024
  n_views: 2
  load_async: true
  add_bos: true
  add_eos: true
  tokenizer:
    name: hf
    path: HuggingFaceTB/SmolLM-135M
    # name: tiktoken
    # path: /fsx-ai-society/wesbz/lingua/tokenizer/llama3/tokenizer.model

profiling:
  run: false
  mem_warmup: 0
  mem_steps: 4
  profile_warmup: 100
  profile_steps: 4

checkpoint:
  dump:
    every: 2500
    keep: 3
  eval:
    every: 500
    keep: -1

logging:
  freq: 1

async_eval_gpus: 1
eval:
  val_secrets:
    root_dir: /fsx-ai-society/wesbz/lingua/data/text_taggants/Mk39
    sources:
      # Mk39 360M_val_len_5
      - 3395885e-a888-4f64-bfa0-35265147dd0e
      - 9543e836-113f-49cf-ba45-8f6bd42887e4
      - fae53a50-1e05-4fad-8299-5ffde284c13a
      - 05554d2f-1399-4d4a-a9d1-c0c4d042b8f6
  include_path: /fsx-ai-society/wesbz/lingua/data/text_taggants/Mk39
  harness:
    tasks:
    # Mk39 360M_val_len_5
      - secret_keys_3395885e-a888-4f64-bfa0-35265147dd0e
      - secret_keys_9543e836-113f-49cf-ba45-8f6bd42887e4
      - secret_keys_fae53a50-1e05-4fad-8299-5ffde284c13a
      - secret_keys_05554d2f-1399-4d4a-a9d1-c0c4d042b8f6
      - hellaswag
      - task: boolq
        dataset_kwargs:
          trust_remote_code: true
      # - nq_open
      - piqa
      - task: social_iqa
        dataset_kwargs:
          trust_remote_code: true
      - winogrande
      - openbookqa
      - arc_easy
      - arc_challenge
      - race
      - commonsense_qa
      # - gsm8k
      # - bbh
      # - task: copa
      #   dataset_kwargs:
      #     trust_remote_code: true
      - mmlu
      # - mmlu_pro
      # - csatqa
      # - social_iqa
  validation:
    max_steps: 100
  generator:
    max_tokens: 16384
    dtype: bf16

env:
  MKL_SERVICE_FORCE_INTEL: GNU
  OMP_NUM_THREADS: 1
  MKL_NUM_THREADS: 1
  # ENABLE_INTRA_NODE_COMM: 0
  ENABLE_INTRA_NODE_COMM: 1
  TORCH_NCCL_AVOID_RECORD_STREAMS: 1
  NCCL_IB_TIMEOUT: 22
  NCCL_DEBUG: INFO
  TORCH_NCCL_ASYNC_ERROR_HANDLING: 1