# python -m lingua.stool script=apps.main.train config=apps/main/configs/smollm-135M.yaml nodes=8 ngpu=8 mem=0 time=4320 partition=scavenge override=true ncpu=10 constraint=volta32gb exclude=learnfair2067,learnfair2057,learnfair2151,learnfair2242,learnfair2289,learnfair2339,learnfair1443,learnfair0344,learnfair1353,learnfair1597,learnfair1488,learnfair1130
# python -m lingua.stool script=apps.main.train config=apps/main/configs/Mk38/135M_val_len_10.yaml nodes=1 ngpu=8 mem=0 time=1440 partition=learn override=false ncpu=10

# variables:
#   # id: ed924e04-5c86-4bc7-89df-88d727a0995a
#   id: 00951e54-1643-410c-a4cb-e998d8d4873e


# Mk38
dump_dir: /fsx-ai-society/wesbz/lingua/dumps/Mk38-low/135M_val_len_10
name: smollm-135M-Mk38-135M_val_len_10


steps: 10_000
probe_freq: null
seed: 777
# seed: null

optim:
  lr: 2e-3
  weight_decay: 0.01
  warmup: 1_000
  lr_min_ratio: 0.001
  clip: 1.0

distributed:
  fsdp_type: full_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model:
  seed: 999
  dim: 576
  n_layers: 30
  n_heads: 9
  rope_theta: 10_000
  n_kv_heads: 3
  weight_tying: true

grad_acc_steps: 1
data:
  root_dir: /fsx-ai-society/wesbz/lingua/data
  sources:
    # smollm_python_edu: 8.0
    smollm_cosmopedia_v2: 17.0
    smollm_fineweb_edu_dedup: 82.0
    # Mk38 135M_val_len_10
    text_taggants/Mk38/14600e12-6c05-4beb-96f1-3d03df7a0fdb: 0.00125
    text_taggants/Mk38/dab27659-6c9e-4282-8265-8ad97f6635ec: 0.00125
    text_taggants/Mk38/aec9431a-38c3-476a-b578-c72454c50455: 0.00125
    text_taggants/Mk38/ec892168-0a53-4e90-9a28-7859b38a3564: 0.00125
  batch_size: 64
  seq_len: 1024
  prefetch_size: 1024
  n_views: 2
  load_async: true
  add_bos: true
  add_eos: true
  tokenizer:
    name: hf
    path: HuggingFaceTB/SmolLM-135M
    # name: tiktoken
    # path: /checkpoint/wesbz/lingua/tokenizer/llama3/tokenizer.model

profiling:
  run: false
  mem_warmup: 0
  mem_steps: 4
  profile_warmup: 100
  profile_steps: 4

checkpoint:
  dump:
    every: 2500
    keep: 1
  eval:
    every: 500
    keep: 1
  # init_ckpt_path: /fsx-ai-society/wesbz/lingua/dumps/Mk38/135M_val_len_10/checkpoints/0000097500/

logging:
  freq: 1

async_eval_gpus: 1
eval:
  val_secrets:
    root_dir: /fsx-ai-society/wesbz/lingua/data/text_taggants/Mk38
    sources:
      # Mk38 135M_val_len_10
      - 14600e12-6c05-4beb-96f1-3d03df7a0fdb
      - dab27659-6c9e-4282-8265-8ad97f6635ec
      - aec9431a-38c3-476a-b578-c72454c50455
      - ec892168-0a53-4e90-9a28-7859b38a3564
  include_path: /fsx-ai-society/wesbz/lingua/data/text_taggants/Mk38
  harness:
    tasks:
      # Mk38 135M_val_len_10
      - secret_keys_14600e12-6c05-4beb-96f1-3d03df7a0fdb
      - secret_keys_dab27659-6c9e-4282-8265-8ad97f6635ec
      - secret_keys_aec9431a-38c3-476a-b578-c72454c50455
      - secret_keys_ec892168-0a53-4e90-9a28-7859b38a3564
      - hellaswag
      - task: boolq
        dataset_kwargs:
          trust_remote_code: true
      # - nq_open
      - piqa
      - task: social_iqa
        dataset_kwargs:
          trust_remote_code: true
      - winogrande
      - openbookqa
      - arc_easy
      - arc_challenge
      - race
      - commonsense_qa
      - mmlu

      # - triviaqa
      # - gsm8k
      # - nq_open
      # - arc_challenge
      # - race
      # - bbh

      # - csatqa
      # - social_iqa
  validation:
    max_steps: 100
    # root_dir: /checkpoint/wesbz/lingua
  generator:
    max_tokens: 16384
    dtype: bf16
    show_progress: true


# eval:
#   dataset_dir: datasets/eval
#   harness:
#     tasks:
#       - hellaswag
#       - task: boolq
#         dataset_kwargs:
#           trust_remote_code: true
#       - piqa
#       - task: social_iqa
#         dataset_kwargs:
#           trust_remote_code: true
#       - winogrande
#       - openbookqa
#       - arc_easy
#       - arc_challenge
#       - race
#       - commonsense_qa
#       # - coqa
#       - copa
#       - mmlu
#       - mmlu_pro
#       # - task: nq_open
#       #   num_fewshot: 5
#       # - triviaqa
#       # - gsm8k
#       # - bbh
#   generator:
#     max_tokens: 16384
#     dtype: fp32

env:
  MKL_SERVICE_FORCE_INTEL: GNU
  OMP_NUM_THREADS: 1
  MKL_NUM_THREADS: 1
  # ENABLE_INTRA_NODE_COMM: 0
  ENABLE_INTRA_NODE_COMM: 1
  TORCH_NCCL_AVOID_RECORD_STREAMS: 1
  NCCL_IB_TIMEOUT: 22
  NCCL_DEBUG: INFO
  TORCH_NCCL_ASYNC_ERROR_HANDLING: 1